---
name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          - macos-latest
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Test
        run: |
          go test -coverprofile=/tmp/coverage.txt $(go list ./...)
          go tool cover -func=/tmp/coverage.txt
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          file: /tmp/coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
